import * as React from "react";
import { generateHankoPath } from "./generateHankoPath";
import "./hanko-seal.css";

export type HankoState =
  | "idle"
  | "preparing"
  | "authenticating"
  | "stamping"
  | "success"
  | "error";

type Props = {
  state?: HankoState;
  size?: number;
  color?: string;
  seed?: string;
  className?: string;
  title?: string;
};

export function HankoSeal({
  state = "idle",
  size = 112,
  color,
  seed,
  className = "",
  title = "Hanko seal",
}: Props) {
  const id = React.useId().replace(/[^a-zA-Z0-9_-]/g, "");
  const gradient = color?.match(/^linear\((#[\da-f]{6}),(#[\da-f]{6})\)$/i);
  const inkColor = gradient?.[1] ?? color ?? "#d64135";

  const gradientId = `${id}-ink-gradient`;
  const formId = `${id}-form`;
  const pillarId = `${id}-pillar`;
  const blockId = `${id}-block`;

  return (
    <div
      className={`hanko-wrap hanko-${state} ${className}`}
      style={{ width: size, height: size, color: inkColor }}
      aria-label={title}
      role="img"
    >
      <svg
        className="hanko-svg"
        viewBox="0 0 1024 1024"
        aria-hidden="true"
      >
        <defs>
          {gradient && <linearGradient id={gradientId} x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor={gradient[1]} />
            <stop offset="100%" stopColor={gradient[2]} />
          </linearGradient>}

          {/* One seal-script form. Top is generated by vertical mirroring. */}
          <path
            id={formId}
            d="
              M 278 744
              H 405
              V 620
              C 405 590, 435 574, 476 574
              H 548
              C 589 574, 619 590, 619 620
              V 744
              H 746
            "
          />

          {/* One pillar. Right side is generated by horizontal mirroring. */}
          <path
            id={pillarId}
            d="M 286 408 V 638"
          />

          {/* One center block. Top is generated by vertical mirroring. */}
          <rect
            id={blockId}
            x="470"
            y="650"
            width="84"
            height="110"
            rx="24"
          />

        </defs>

        <g className="hanko-ink">
          <g
            fill="none"
            stroke={gradient ? `url(#${gradientId})` : "currentColor"}
            strokeWidth="76"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            {/* Outer frame */}
            <rect
              className="hanko-outline"
              x="122"
              y="122"
              width="780"
              height="780"
              rx="132"
            />

            {seed ? <path className="hanko-generated-glyph" d={generateHankoPath(seed)} /> : <>
              {/* Upper form: vertically mirrored */}
              <use
                className="hanko-glyph hanko-glyph-top"
                href={`#${formId}`}
                transform="translate(0 1024) scale(1 -1)"
              />

              {/* Lower form */}
              <use
                className="hanko-glyph hanko-glyph-bottom"
                href={`#${formId}`}
              />

              {/* Left pillar */}
              <use
                className="hanko-pillar hanko-pillar-left"
                href={`#${pillarId}`}
              />

              {/* Right pillar: horizontally mirrored */}
              <use
                className="hanko-pillar hanko-pillar-right"
                href={`#${pillarId}`}
                transform="translate(1024 0) scale(-1 1)"
              />
            </>}
          </g>

          {!seed && <g fill={gradient ? `url(#${gradientId})` : "currentColor"}>
            {/* Lower block */}
            <use
              className="hanko-block hanko-block-bottom"
              href={`#${blockId}`}
            />

            {/* Upper block: vertically mirrored */}
            <use
              className="hanko-block hanko-block-top"
              href={`#${blockId}`}
              transform="translate(0 1024) scale(1 -1)"
            />
          </g>}
        </g>

        {/* Only appears during physical stamp impact */}
        <g
          className="hanko-splatter"
          fill={gradient ? `url(#${gradientId})` : "currentColor"}
        >
          <circle cx="92" cy="510" r="9" />
          <circle cx="936" cy="474" r="7" />
          <circle cx="900" cy="852" r="5" />
          <circle cx="154" cy="176" r="5" />
          <circle cx="836" cy="126" r="4" />
          <circle cx="214" cy="904" r="6" />
          <circle cx="758" cy="930" r="4" />
        </g>
      </svg>

      <span
        className="hanko-impact"
        aria-hidden="true"
      />
    </div>
  );
}
